daycareBlitz2 = {
	{'w',30},
	-- Next! prepare for pidgeot, tentacruel, golbat, machoke, kadabra
	-- then evolve tentacool and prepare for dragonair
	{'s',5},
	{'w',60},
	{'walkUp',1},
	{'a',5},
	{'w',120},
	{'a',5},
	{'w',30},
	{'walkDown',1},
	{'a',5},
	{'w',120},
	{'flyRight',3},
	{'a',5},
	{'w',480},
	{'walkLeft',8},
	{'walkUp',25},
	{'walkRight',18},
	{'walkUp',11},
	{'w',180},
	{'walkUp',8},
	{'w',180},
	{'walkUp',4},
	{'walkRight',6},
	{'walkUp',35},
	{'walkLeft',3},
	{'walkDown',3},
	{'w',60},
	{'walkDown',6},
	{'grassDown',2},
	{'walkDown',2},
	{'grassDown',2},
	{'walkDown',2},
	{'grassDown',2},
	{'walkDown',3},
	{'w',60},
	{'walkDown',6},
	{'walkLeft',5},
	{'walkUp',1},
	{'w',180}, -- in daycare
	{'walkRight',2},
	{'walkDown',1},
	{'resetMenu',1},
	{'walkRight',6}, -- to PC
	{'walkUp',6},
	{'talk',5},
	{'walkDown',2},
	{'a',5},
	{'w',120}, -- pull out tentacool, zubat, abra and machop
	{'walkRight',2},
	{'talk',2},
	{'walkUp',2},
	{'a',5},
	{'w',120},
	{'talk',2},
	{'b',5},
	{'w',120},
	{'walkDown',2},
	{'walkRight',1},
	{'talk',2},
	{'walkUp',4},
	{'a',5},
	{'w',120},
	{'walkUp',1},
	{'talk',2},
	{'walkUp',3},
	{'talk',2},
	{'b',5},
	{'w',120},
	{'walkDown',1},
	{'walkLeft',1},
	{'w',60},
	{'talk',2},
	{'walkUp',3},
	{'a',5},
	{'w',120},
	{'walkUp',2},
	{'talk',2},
	{'b',5},
	{'w',120},
	{'walkDown',2},
	{'walkRight',2},
	{'talk',2},
	{'walkUp',4},
	{'a',5},
	{'w',120},
	{'walkUp',3},
	{'talk',2},
	{'b',5},
	{'w',120},
	{'walkRight',2},
	{'talk',2},
	{'mashB',8}, -- everyone out of box. ready to run!

	{'walkLeft',6},
	{'walkDown',4},
	{'walkLeft',2},
	{'walkUp',1}, -- drop off pidgeotto
 	-- dont know exactly how much exp pidgey got. between 8-26
	-- so have 3805-3823 EXP
	-- Need 40006 max. 
	-- I get 17932 
	{'talk',4}, -- drop off pidgeotto
	{'w',60},
	{'walkDown',1},
	{'talk',4},
	{'leaveDaycare',1},
	{'s',5},
	{'w',60},
	{'walkDown',3},
	{'a',5},
	{'w',120},
	{'walkRight',1},
	{'talk',2},
	{'w',60},
	{'bike_daycare',305},
	{'walkDown',44},
	{'walkUp',44},
	{'returnDaycare',1},
	{'w',60}, -- get pidgeotto back
	{'talk',7},
	{'w',60},
	-- tentacool might be level 5 (156) might be higher. need to get him to level 29 at least and then use rare candy
	-- need 20486. can overshoot so I will do 259 bike routes
	{'talk',4}, -- drop off tentacool
	{'w',60},
	{'walkDown',1},
	{'talk',4},
	{'leaveDaycare',1},
	{'s',5},
	{'w',60},
	{'walkDown',3},
	{'a',5},
	{'w',120},
	{'talk',2},
	{'w',60},
	{'bike_daycare',259},
	{'walkDown',24},
	{'walkUp',24},
	{'returnDaycare',1},
	{'w',60}, -- get tentacool back
	{'talk',7},
	{'w',60},
	-- golbat 
	-- need 9647. 80 cycles, get in 100 extra steps
	{'talk',4}, -- drop off zubat
	{'w',60},
	{'walkDown',1},
	{'talk',4},
	{'leaveDaycare',1},
	{'s',5},
	{'w',60},
	{'walkDown',3},
	{'a',5},
	{'w',120},
	{'talk',2},
	{'w',60},
	{'bike_daycare',80},
	{'walkDown',52},
	{'walkUp',52},
	{'returnDaycare',1},
	{'w',60}, -- get zubat back
	{'talk',7},
	{'w',60},
	-- machoke
	-- dont even need to level him just get 4532 EXP. 37 cycles, 60 extra steps 
	{'talk',4}, -- drop off machop
	{'w',60},
	{'walkDown',1},
	{'talk',4},
	{'leaveDaycare',1},
	{'s',5},
	{'w',60},
	{'walkDown',3},
	{'a',5},
	{'w',120},
	{'talk',2},
	{'w',60},
	{'bike_daycare',37},
	{'walkDown',31},
	{'walkUp',31},
	{'returnDaycare',1},
	{'w',60}, -- get machop back
	{'talk',6},
	{'w',60},
	-- kadabra 
	-- need 3677 EXP
	{'talk',4}, -- drop off abra
	{'w',60},
	{'walkDown',1},
	{'talk',4},
	{'leaveDaycare',1},
	{'s',5},
	{'w',60},
	{'walkDown',3},
	{'a',5},
	{'w',120},
	{'talk',2},
	{'w',60},
	{'bike_daycare',17},
	{'walkDown',2},
	{'walkUp',2},
	{'returnDaycare',1},
	{'w',60}, -- get abra back
	{'talk',7},
	{'w',60},	
	-- evolve tentacool
	{'s',5},
	{'w',60},
	{'walkUp',4},
	{'a',5},
	{'w',120}, 
	{'walkLeft',1}, -- rare candy
	{'talk',2},
	{'w',60},
	{'walkDown',2},
	{'a',5},
	{'w',300},
	{'a',5},
	{'w',240},
	{'talk',5},
	{'b',5},
	{'w',90},
	{'talk',2},
	{'w',1500},
	{'b',5},
	{'w',90},
	{'b',5},
	{'w',90},
	{'b',5},
	{'w',90},
	{'b',5},
	{'w',90},
	{'a',5},
	{'w',90},
	{'mashB',20}, -- i have tentacruel now!
	{'w',30}, -- go to PC to grab dratini
	{'walkRight',3},
	{'walkUp',4},
	{'walkRight',5},
	{'walkUp',1},
	{'talk',5},
	{'walkDown',2},
	{'a',5},
	{'w',180},
	{'walkRight',4},
	{'talk',2},
	{'walkUp',2},
	{'a',5},
	{'w',120},
	{'walkUp',4},
	{'talk',2},
	{'walkDown',1},
	{'talk',2},
	{'w',60},
	{'b',5},
	{'w',120},
	{'walkRight',4},
	{'talk',2},
	{'mashB',10},
	{'w',30},
	{'walkLeft',6},
	{'walkDown',4},
	{'walkLeft',2},
	{'walkUp',1},
	-- dratini starts at 18. need lvl 30. in the slow group :(
	-- need 26459 EXP
	{'talk',4}, -- drop off dratini
	{'w',60},
	{'walkDown',1},
	{'talk',4},
	{'leaveDaycare',1},
	{'s',5},
	{'w',60},
	{'a',5},
	{'w',120},
	{'walkRight',1},
	{'talk',2},
	{'w',60},
	{'bike_daycare',223},
	{'walkDown',21},
	{'walkUp',21},
	{'returnDaycare',1},
	{'w',60}, -- get dratini back
	{'talk',7},
	{'w',60},

}
