daycareBlitz1 = {
	{'w',30},
	-- go to daycare
	-- train oddish  to LVL 20 1 EXP off LVL 21     4845 EXP
	-- train kabuto  to LVL 39 1 EXP off LVL 40	   61166 EXP
	-- train pidgey  to LVL 17 1 EXP off LVL 18     3662 EXP
	-- train spearow to LVL 19 1 EXP off LVL 20     7487 EXP
	-- train kakuna  to LVL  9 1 EXP off LVL 10      783 EXP
	--
	-- ENTER UNDERGROUND 	=  20 STEPS
	-- FIRST ROUND 			= 117 STEPS 
	-- OTHER ROUNDS 		= 118 STEPS
	-- RETURN TO DAYCARE	=  85 STEPS
	--
	-- ODDISH  =  40 rounds + 21 extra steps
	-- KABUTO  = 517 rounds + 55 extra steps
	-- PIDGEY  =  30 rounds + 16 extra steps
	-- SPEAROW =  62 rounds + 65 extra steps
	-- KAKUNA  =   5 rounds + 69 extra steps
	{'walkDown',4},
	{'w',180}, -- switch articuno to front, fly to cerulean
	{'s',5},
	{'w',60},
	{'walkUp',1},
	{'a',5},
	{'w',120},
	{'walkDown',1},
	{'a',5},
	{'w',30},
	{'walkDown',2},
	{'a',5},
	{'w',30},
	{'walkUp',1},
	{'a',5},
	{'w',90},
	{'a',5},
	{'w',30},
	{'walkDown',1},
	{'a',5},
	{'w',120},
	{'flyUp',6},
	{'a',5},
	{'w',480}, -- walk to daycare
	{'walkLeft',4},
	{'walkDown',11},
	{'walkRight',8},
	{'walkDown',2},
	{'talk',4},
	{'w',300},
	{'walkDown',5},
	{'w',60},
	{'walkDown',7},
	{'w',60},
	{'walkDown',4},
	{'w',60},
	{'walkDown',1}, -- repel
	{'w',60},
	{'b',5},
	{'w',30},
	{'walkDown',2}, -- not going to repel.
	{'grassDown',2},
	{'walkDown',3},
	{'w',60},
	{'walkDown',6},
	{'walkLeft',4},
	{'walkUp',1},
	{'w',180}, -- reset menu
	{'walkRight',2},
	{'walkDown',1},
	{'resetMenu',1},
	{'s',5},
	{'w',60},
	{'walkUp',5},
	{'b',5},
	{'w',30},
	{'walkRight',7}, -- to the PC!
	{'walkUp',6},
	{'talk',5},
	{'walkDown',2},
	{'a',5},
	{'w',180},
	{'walkDown',1},
	{'walkRight',2},
	{'talk',2},
	{'w',30},
	{'walkUp',3},
	{'a',5},
	{'w',120},
	{'walkUp',2},
	{'talk',2},
	{'w',30},
	{'walkUp',1},
	{'talk',2},
	{'w',30},
	{'walkUp',1},
	{'talk',2},
	{'w',30},
	{'walkDown',1},
	{'talk',2},
	{'w',30},
	{'b',5},
	{'w',60},
	{'walkRight',4},
	{'walkDown',1},
	{'talk',2},
	{'w',30},
	{'walkUp',3},
	{'a',5},
	{'w',120},
	{'walkUp',1},
	{'talk',2},
	{'w',30},
	{'b',5},
	{'w',60},
	{'walkDown',2},
	{'walkRight',3},
	{'talk',2},
	{'w',30},
	{'walkUp',4},
	{'a',5},
	{'w',120},
	{'talk',2},
	{'w',30},
	{'b',5},
	{'w',60},
	{'walkRight',2},
	{'walkDown',1},
	{'talk',2},
	{'mashB',10},
	{'walkLeft',6},
	{'walkDown',4},
	{'walkLeft',2},
	{'walkUp',1},
	{'talk',4}, -- drop off oddish
	{'w',60},
	{'walkDown',1},
	{'talk',4},
	{'leaveDaycare',1},
	{'s',5},
	{'w',60},
	{'walkDown',1},
	{'a',5},
	{'w',120},
	{'walkRight',1},
	{'talk',2},
	{'w',60},
	{'bike_daycare',40}, -- 20 extra steps
	{'walkDown',11},
	{'walkUp',11},
	{'returnDaycare',1},
	{'w',60}, -- get oddish back. 2EXP off
	{'talk',7},
	{'w',60},
	{'talk',4}, -- drop off Kabuto
	{'w',60},
	{'walkDown',1},
	{'talk',4},
	{'leaveDaycare',1},
	{'s',5},
	{'w',60},
	{'walkDown',3},
	{'a',5},
	{'w',120},
	{'talk',2},
	{'w',60},
	{'bike_daycare',517}, -- 56 extra steps
	{'walkDown',28},
	{'walkUp',28},
	{'returnDaycare',1},
	{'w',60}, -- get kabuto back. 3EXP off
	{'talk',7},
	{'w',60},
	{'talk',4}, -- drop off pidgey
	{'w',60},
	{'walkDown',1},
	{'talk',4},
	{'leaveDaycare',1},
	{'s',5},
	{'w',60},
	{'walkDown',3},
	{'a',5},
	{'w',120},
	{'talk',2},
	{'w',60},
	{'bike_daycare',30}, -- 16 extra steps
	{'walkDown',10},
	{'walkUp',10},
	{'returnDaycare',1},
	{'w',60}, -- get pidgey back. 1EXP off
	{'talk',7},
	{'w',60},
	{'w',30},
	{'talk',4}, -- drop off spearow
	{'w',60},
	{'walkDown',1},
	{'talk',4},
	{'leaveDaycare',1},
	{'s',5},
	{'w',60},
	{'walkDown',3},
	{'a',5},
	{'w',120},
	{'talk',2},
	{'w',60},
	{'bike_daycare',62}, -- 66 extra steps
	{'walkDown',34},
	{'walkUp',34},
	{'returnDaycare',1},
	{'w',60}, -- get spearow back. 2EXP off
	{'talk',7},
	{'w',60},
	{'w',30},
	{'talk',4}, -- drop off kakuna
	{'w',60},
	{'walkDown',1},
	{'talk',4},
	{'leaveDaycare',1},
	{'s',5},
	{'w',60},
	{'walkDown',3},
	{'a',5},
	{'w',120},
	{'talk',2},
	{'w',60},
	{'bike_daycare',5}, 
	{'walkDown',45},
	{'walkUp',45},
	{'returnDaycare',1},
	{'w',60}, -- get kakuna back. 2EXP off
	{'talk',7},
	{'w',60},
}
