farfetchd = {
	{'w',30},
	-- fly to vermillion
	-- heal
	-- take clefairy, oddish and spearow out of box
	-- trade for farfetchd
	{'s',5},
	{'w',60},
	{'a',5},
	{'w',120},
	{'walkDown',1},
	{'a',5},
	{'w',30},
	{'walkDown',1},
	{'a',5},
	{'w',120},
	{'flyDown',8},
	{'a',5},
	{'w',480},
	{'walkUp',1}, -- in vermillion pokemon center
	{'w',180},
	{'walkUp',4},
	{'talk',3},
	{'w',420},
	{'mashB',8},
	{'walkRight',5},
	{'walkUp',3},
	{'talk',5}, -- PC. get clefairy, spearow, oddish
	{'walkDown',2},
	{'a',5},
	{'w',180},
	{'walkRight',3},
	{'talk',2},
	{'walkUp',2},
	{'a',5},
	{'w',120},
	{'talk',2},
	{'b',5},
	{'w',120},
	{'walkDown',1},
	{'walkRight',3},
	{'talk',2},
	{'walkUp',3},
	{'a',5},
	{'w',120},
	{'walkUp',1},
	{'talk',2},
	{'b',5},
	{'w',120},
	{'walkLeft',2},
	{'walkDown',2},
	{'talk',2},
	{'walkUp',4},
	{'a',5},
	{'w',120},
	{'walkUp',3},
	{'talk',2},
	{'b',5},
	{'w',120},
	{'walkRight',3},
	{'talk',2},
	{'mashB',10}, -- done with pc
	{'walkDown',4},
	{'walkLeft',5},
	{'walkDown',5},
	{'w',180},
	{'walkDown',3},
	{'walkRight',16},
	{'walkDown',4},
	{'walkLeft',9},
	{'walkDown',6},
	{'walkLeft',4},
	{'walkUp',1},
	{'w',180}, -- farfetchd house
	{'walkUp',2},
	{'talk',3},
	{'w',60},
	{'walkUp',3},
	{'a',5},
	{'w',45*60}, -- 45 seconds
	{'a',5},
	{'w',120},
	{'a',5},
	{'w',30}, -- done here
}
