defEVs = {
	{'w',30},
	-- Machamp needs 252 Def EVs. tangela south of pallet give 1 each so 2 with macho brace
	-- Brick Break and Strength guaranteed 1-shot. 15 PP each, so 60 EVs per cycle
	-- 4 cycles + 6 encounters is 252
	-- first grab vileplume from PC in viridian (could be anywhere really)
	{'s',5},
	{'w',60},
	{'walkUp',1},
	{'a',5},
	{'w',120},
	{'walkUp',2},
	{'a',5},
	{'w',30},
	{'walkDown',1},
	{'a',5},
	{'w',120},
	{'flyLeft',7},
	{'flyDown',2},
	{'a',5},
	{'w',480},
	{'walkUp',1},
	{'w',180},
	{'walkUp',4},
	{'walkRight',5},
	{'walkUp',3},
	{'talk',5},
	{'walkDown',2},
	{'talk',3},
	{'walkUp',2},
	{'a',5},
	{'w',120},
	{'walkUp',2},
	{'talk',2},
	{'b',5},
	{'w',120},
	{'talk',2},
	{'walkUp',2},
	{'a',5},
	{'w',120},
	{'talk',2},
	{'walkDown',2},
	{'talk',2},
	{'walkDown',2},
	{'talk',2},
	{'walkDown',1},
	{'talk',2},
	{'mashB',12}, -- done in box
	{'walkDown',3},
	{'walkLeft',5},
	{'walkDown',6},
	{'w',180}, -- fly down to pallet
	{'s',5},
	{'w',60},
	{'a',5},
	{'w',120},
	{'walkUp',2},
	{'a',5},
	{'w',30},
	{'walkDown',3},
	{'a',5},
	{'w',30},
	{'walkDown',1},
	{'talk',2}, -- take macho brace from articuno
	{'a',5},
	{'w',30},
	{'walkDown',1},
	{'a',5},
	{'w',120},
	{'flyDown',3},
	{'a',5},
	{'w',480}, 
	{'walkRight',5},
	{'walkDown',5},
	{'walkLeft',5},
	{'walkDown',8},
	{'walkRight',1},
	{'talk',3}, -- give macho brace to machamp, repel
	{'w',300},
	{'s',5},
	{'w',60},
	{'walkDown',1},
	{'a',5},
	{'w',120},
	{'walkLeft',1},
	{'talk',3},
	{'walkDown',17},
	{'a',5},
	{'w',30},
	{'walkDown',1},
	{'talk',3},
	{'b',5},
	{'w',180},
	{'walkUp',1},
	{'b',5},
	{'w',60},
	{'walkDown',7},
	{'walkRight',5},
	{'w',90}, --ev cycle can begin here
	{'evCycle',15},
	{'evCycle2',15},
	-- 60 EVs. Fly to pallet
	{'s',5},
	{'w',60},
	{'a',5},
	{'w',120},
	{'walkUp',2},
	{'a',5},
	{'w',30},
	{'walkDown',1},
	{'a',5},
	{'w',120},
	{'flyUp',1},
	{'a',5},
	{'w',480},

	{'walkUp',1}, -- mom heal
	{'w',180},
	{'walkRight',5},
	{'walkUp',4},
	{'talk',2},
	{'w',420},
	{'talk',2},
	{'walkDown',4},
	{'walkLeft',5},
	{'walkDown',1},
	{'w',180},

	{'walkRight',5},
	{'walkDown',5},
	{'walkLeft',5},
	{'walkDown',8},
	{'walkRight',1},
	{'talk',3}, 
	{'w',300},
	{'walkDown',7},
	{'walkRight',5},
	{'w',90}, --ev cycle can begin here
	{'evCycle',15},
	{'evCycle2',15},
	-- 120 EV
	{'s',5},
	{'w',60},
	{'a',5},
	{'w',120},
	{'walkUp',2},
	{'a',5},
	{'w',30},
	{'walkDown',1},
	{'a',5},
	{'w',120},
	{'flyUp',1},
	{'a',5},
	{'w',480},

	{'walkUp',1}, -- mom heal
	{'w',180},
	{'walkRight',5},
	{'walkUp',4},
	{'talk',2},
	{'w',420},
	{'talk',2},
	{'walkDown',4},
	{'walkLeft',5},
	{'walkDown',1},
	{'w',180},


	{'walkRight',5},
	{'walkDown',5},
	{'walkLeft',5},
	{'walkDown',8},
	{'walkRight',1},
	{'talk',3}, 
	{'w',300},
	{'walkDown',7},
	{'walkRight',5},
	{'w',90}, --ev cycle can begin here
	{'evCycle',15},
	{'evCycle2',15},
	-- 180 EV
	{'s',5},
	{'w',60},
	{'a',5},
	{'w',120},
	{'walkUp',2},
	{'a',5},
	{'w',30},
	{'walkDown',1},
	{'a',5},
	{'w',120},
	{'flyUp',1},
	{'a',5},
	{'w',480},

	{'walkUp',1}, -- mom heal
	{'w',180},
	{'walkRight',5},
	{'walkUp',4},
	{'mashB',3}, -- repel lol
	{'talk',2},
	{'w',420},
	{'talk',2},
	{'walkDown',4},
	{'walkLeft',5},
	{'walkDown',1},
	{'w',180},

	{'walkRight',5},
	{'walkDown',5},
	{'walkLeft',5},
	{'walkDown',8},
	{'walkRight',1},
	{'talk',3}, 
	{'w',300}, -- repel
	{'s',5},
	{'w',60},
	{'walkDown',1},
	{'a',5},
	{'w',120},
	{'walkUp',16},
	{'talk',3},
	{'b',5},
	{'w',120},
	{'walkUp',1},
	{'b',5},
	{'w',90},

	{'walkDown',7},
	{'walkRight',5},
	{'w',90}, --ev cycle can begin here
	{'evCycle',15},
	{'evCycle2',15},
	-- 240 EV
	{'s',5},
	{'w',60},
	{'a',5},
	{'w',120},
	{'walkUp',2},
	{'a',5},
	{'w',30},
	{'walkDown',1},
	{'a',5},
	{'w',120},
	{'flyUp',1},
	{'a',5},
	{'w',480},

	{'walkUp',1}, -- mom heal
	{'w',180},
	{'walkRight',5},
	{'walkUp',4},
	{'talk',2},
	{'w',420},
	{'talk',2},
	{'walkDown',4},
	{'walkLeft',5},
	{'walkDown',1},
	{'w',180},

	{'walkRight',5},
	{'walkDown',5},
	{'walkLeft',5},
	{'walkDown',8},
	{'walkRight',1},
	{'talk',3}, 
	{'w',300}, 	
	{'walkDown',7},
	{'walkRight',5},
	{'w',90}, -- last ev cycle can begin here
	{'evCycle',6},
	-- 252 EV
	{'w',30},
}
