itemFinale = {
	{'w',30},
	-- need to grab
	-- 1 CHERI BERRY			SEVAULT CAVERN
	-- 2 LUM BERRIES			RTE 8, RTE 23
	-- 1 ASPEAR BERRIES			RTE 23
	-- THUNDER TM				POWER PLANT
	-- 
	-- need to buy
	-- HYPER BEAM TM			CELADON DEPT STORE F2
	-- BRICK BREAK TM			CELADON DEPT STORE F2
	-- 8 X SPECIALS				CELADON DEPT STORE F5
	-- 7 X ATTACKS				CELADON DEPT STORE F5
	-- 6 X SPEEDS				CELADON DEPT STORE F5
	-- 2 X ACCS					CELADON DEPT STORE F5
	-- 5 FULL RESTORES			LEAGUE SHOP (buy later)
	-- 3 REVIVES				LEAGUE SHOP (buy later)
	--
	-- FIRST CHERI BERRY. HEAD TO SEVEN ISLAND
	{'walkLeft',3},
	{'walkDown',16},
	{'w',180},
	{'walkDown',2},
	{'a',5},
	{'w',180},
	{'walkUp',2},
	{'a',5},
	{'w',30},
	{'walkDown',2},
	{'talk',2},
	{'w',480},
	{'walkUp',4},
	{'w',180},
	{'walkUp',2},
	{'walkLeft',9},
	{'walkDown',15},
	{'walkLeft',4},
	{'walkDown',4},
	{'s',5}, -- switch jolteon and articuno to first two, use a repel
	{'w',30},
	{'a',5},
	{'w',120},
	{'a',5},
	{'w',30},
	{'walkDown',2},
	{'a',5},
	{'w',30},
	{'walkDown',3},
	{'a',5},
	{'w',180},
	{'b',5},
	{'w',120},
	{'walkDown',1},
	{'a',5},
	{'w',120}, -- teach surf and rock smash to slowbro
	{'a',5},
	{'w',30},
	{'a',5},
	{'w',120},
	{'walkDown',1},
	{'a',5},
	{'w',30},
	{'a',5},
	{'w',180},
	{'walkUp',3},
	{'talk',5},
	{'w',60},
	{'a',5},
	{'w',240},
	{'talk',4},
	{'w',360},
	{'walkDown',2},
	{'a',5},
	{'w',30},
	{'a',5},
	{'w',180},
	{'talk',5},
	{'w',60},
	{'walkDown',1},
	{'a',5},
	{'w',240},
	{'talk',4},
	{'w',360},
	{'b',5},
	{'w',120},
	{'walkLeft',1},
	{'walkUp',8},
	{'talk',3},
	{'mashB',8},
	{'walkDown',6},
	{'walkRight',8},
	{'walkUp',3},
	{'walkRight',5},
	{'walkDown',13},
	{'walkLeft',5},
	{'walkDown',3},
	{'walkLeft',1},
	{'talk',3}, -- spinner, might gain or lose a step
	{'w',480},
	{'a',5},
	{'w',480},
	{'a',5},
	{'w',30},
	{'a',5},
	{'w',30},
	{'mashB',30},
	{'a',5},
	{'w',30},
	{'a',5},
	{'w',30},
	{'mashB',30},
	{'walkLeft',1},
	{'w',60},
	{'walkDown',5},
	{'walkRight',4},
	{'walkUp',3},
	{'walkRight',5},
	{'walkDown',4},
	{'walkRight',4},
	{'walkUp',3},
	{'walkRight',4},
	{'walkDown',3},
	{'walkRight',5},
	{'walkUp',3},
	{'walkRight',9},
	{'walkUp',3},
	{'walkLeft',4},
	{'walkUp',3},
	{'walkRight',8},
	{'walkDown',10},
	{'mashB',3},
	{'walkLeft',2},
	{'mashB',3},
	{'walkDown',2},
	{'mashB',3},
	{'walkDown',11},
	{'s',5},
	{'w',60}, -- repel
	{'a',5},
	{'w',120},
	{'talk',3},
	{'mashB',8},
	{'walkLeft',4},
	{'walkDown',6},
	{'walkLeft',2},
	{'talk',3},
	{'w',300},
	{'walkLeft',5},
	{'walkUp',4},
	{'walkLeft',4},
	{'walkDown',8},
	{'walkLeft',1},
	{'talk',3}, -- spinner, might gain or lose a step
	{'w',480},
	{'a',5},
	{'w',480},
	{'a',5},
	{'w',30},
	{'a',5},
	{'w',30},
	{'mashB',30},
	{'a',5},
	{'w',30},
	{'a',5},
	{'w',30},
	{'mashB',30},
	{'a',5},
	{'w',30},
	{'a',5},
	{'w',30},
	{'mashB',30},
	{'walkLeft',1},
	{'w',60},

	-- this trainer's chansey has 
	-- MINIMIZE, DEF CURL, SOFTBOILED, EGG BOMB
	-- Guaranteed OHKO with machamp vital throw 
	{'s',5}, -- switch to machamp
	{'w',60},
	{'walkUp',1},
	{'a',5},
	{'w',120},
	{'a',5},
	{'w',30},
	{'walkDown',2},
	{'a',5},
	{'w',30},
	{'walkUp',2},
	{'a',5},
	{'w',120},
	{'mashB',8},
	{'walkDown',2},
	{'walkLeft',1},
	{'talk',3}, -- spinner, might gain or lose a step
	{'w',480},
	{'a',5},
	{'w',480},
	{'a',5},
	{'w',30},
	{'a',5},
	{'w',30},
	{'mashB',50},
	{'walkLeft',1},
	{'w',60},
	{'walkDown',7},
	{'walkRight',5},
	{'walkDown',6},
	{'walkRight',3},
	{'walkDown',6}, -- switch jolt to front
	{'s',5},
	{'w',60},
	{'a',5},
	{'w',120},
	{'a',5},
	{'w',30},
	{'walkDown',1},
	{'a',5},
	{'w',30},
	{'walkDown',1},
	{'a',5},
	{'w',120},
	{'mashB',8},
	{'walkDown',9},
	{'mashA',500},
	{'mashB',30},
	{'a',5},
	{'w',30},
	{'a',5},
	{'w',30},
	{'mashB',40},
	{'a',5},
	{'w',30},
	{'a',5},
	{'w',30},
	{'mashB',40},
	{'a',5},
	{'w',30},
	{'a',5},
	{'w',30},
	{'mashB',40},
	{'a',5},
	{'w',30},
	{'a',5},
	{'w',30},
	{'mashB',40},
	{'walkRight',3},
	{'walkDown',6},
	{'walkRight',3},
	{'a',5},
	{'w',240},
	{'mashB',3}, -- cheri bery!	might have +-3 steps on repel

	-- NEXT THUNDER TM. HEAD TO POWER PLANT
	
	{'s',5},
	{'w',60},
	{'a',5},
	{'w',120},
	{'walkUp',2},
	{'a',5},
	{'w',30},
	{'walkDown',1},
	{'a',5},
	{'w',120},
	{'flyLeft',1},
	{'flyUp',3},
	{'a',5},
	{'w',480},
	{'walkLeft',5},
	{'walkDown',8},
	{'walkRight',9},
	{'walkDown',4},
	{'w',180},
	{'walkDown',2},
	{'talk',3},
	{'w',480}, -- fly to rock tunnel 
	{'s',5},
	{'w',60},
	{'a',5},
	{'w',120},
	{'walkUp',2},
	{'a',5},
	{'w',30},
	{'walkDown',1},
	{'a',5},
	{'w',120},
	{'flyRight',4},
	{'flyUp',6},
	{'a',5},
	{'w',480},
	{'walkRight',5},
	{'walkUp',18},
	{'w',60},
	{'walkLeft',2},
	{'walkUp',3},
	{'walkLeft',12},
	{'walkUp',8},
	{'walkRight',14},
	{'talk',3},
	{'w',300},
	{'s',5}, -- repel
	{'w',60},
	{'walkDown',1},
	{'a',5},
	{'w',120},
	{'talk',3},
	{'mashB',8},
	{'walkDown',42},
	{'walkLeft',2},
	{'w',60},
	{'walkLeft',11},
	{'walkUp',6},
	{'w',300}, -- power plant
	{'walkUp',7},
	{'walkRight',2},
	{'walkUp',5},
	{'walkLeft',4},
	{'walkUp',6},
	{'walkRight',7},
	{'walkUp',5},
	{'walkRight',6},
	{'walkDown',5},
	{'walkLeft',2},
	{'walkDown',5},
	{'mashB',3}, -- repel
	{'s',5},
	{'w',60},
	{'a',5},
	{'w',120},
	{'talk',3},
	{'mashB',8},
	{'walkDown',1},
	{'walkRight',7},
	{'walkDown',5},
	{'walkRight',5},
	{'walkUp',2},
	{'walkRight',6},
	{'walkDown',3},
	{'walkRight',6},
	{'walkUp',3},
	{'walkRight',6},
	{'walkDown',7},
	{'walkRight',6},
	{'walkDown',3},
	{'walkRight',4},
	{'walkUp',1},
	{'a',5},
	{'w',240},
	{'mashB',3}, -- escape rope
	{'s',5},
	{'w',60},
	{'a',5},
	{'w',120},
	{'walkDown',8},
	{'a',5},
	{'w',30},
	{'a',5},
	{'w',240},
	{'a',5},
	{'w',480},
	
	-- NEXT LUM BERRY. HEAD TO RTE 8

	{'s',5},
	{'w',60},
	{'walkUp',1},
	{'a',5},
	{'w',120},
	{'walkUp',2},
	{'a',5},
	{'w',30},
	{'walkDown',1},
	{'a',5},
	{'w',120},
	{'flyDown',2},
	{'flyLeft',4},
	{'a',5},
	{'w',480},
	{'walkDown',1},
	{'walkRight',29},
	{'walkUp',14},
	{'walkRight',8},
	{'w',180},
	{'walkRight',1},
	{'mashB',3},
	{'walkRight',11},
	{'w',180}, -- RTE 8
	{'walkRight',11},
	{'walkDown',5},
	{'walkRight',11},
	{'walkUp',5},
	{'walkRight',5},
	{'walkDown',6},
	{'walkRight',1},
	{'talk',4},
	{'w',300},
	{'walkRight',2},
	{'walkUp',5},
	{'walkRight',2}, -- repel
	{'s',5},
	{'w',60},
	{'walkDown',1},
	{'a',5},
	{'w',120},
	{'walkUp',8},
	{'talk',3},
	{'mashB',8},
	{'walkRight',2},
	{'a',5},
	{'w',240},
	{'mashB',3},

	-- NEXT ASPEAR BERRY. HEAD UP RTE 23
	
	{'s',5},
	{'w',60},
	{'walkUp',1},
	{'a',5},
	{'w',120},
	{'walkUp',2},
	{'a',5},
	{'w',30},
	{'walkDown',1},
	{'a',5},
	{'w',120},
	{'flyLeft',12},
	{'flyDown',2},
	{'a',5},
	{'w',480},
	{'walkLeft',4},
	{'walkUp',9},
	{'walkLeft',30},
	{'walkDown',6},
	{'walkLeft',6},
	{'walkUp',9},
	{'walkLeft',23},
	{'walkDown',3},
	{'w',60},
	{'walkDown',4},
	{'walkLeft',10},
	{'walkUp',4},
	{'mashB',3}, -- repel
	{'walkRight',5},
	{'walkUp',4},
	{'walkLeft',3},
	{'walkUp',3},
	{'w',180},
	{'walkUp',9},
	{'w',180}, -- RTE 23
	{'walkUp',3},
	{'walkRight',6},
	{'walkUp',10},
	{'walkLeft',7},
	{'walkUp',10},
	{'walkRight',4},
	{'walkUp',9},
	{'walkRight',3},
	{'walkUp',7},
	{'talk',3},
	{'w',300}, -- repel
	{'s',5},
	{'w',60},
	{'walkDown',1},
	{'a',5},
	{'w',120},
	{'talk',3},
	{'mashB',8},
	{'walkRight',2},
	{'walkUp',14},
	{'walkLeft',7},
	{'walkUp',21},
	{'walkRight',3},
	{'walkUp',7},
	{'w',60},
	{'walkRight',2},
	{'walkUp',11},
	{'a',5},
	{'w',240},
	{'mashB',3},

	-- NEXT SECOND LUM BERRY. HEAD TO LEAGUE
	
	{'s',5},
	{'w',60},
	{'walkUp',1},
	{'a',5},
	{'w',120},
	{'walkUp',2},
	{'a',5},
	{'w',30},
	{'walkDown',1},
	{'a',5},
	{'w',120},
	{'flyUp',2},
	{'a',5},
	{'w',480},
	{'walkDown',15},
	{'walkRight',5},
	{'walkDown',10},
	{'walkLeft',2},
	{'walkDown',8},
	{'walkLeft',7},
	{'mashB',3},
	{'walkLeft',4},
	{'a',5},
	{'w',240},
	{'mashB',3},

	-- FINALLY, DEPT STORE
	
	{'s',5},
	{'w',60},
	{'a',5},
	{'w',120},
	{'walkUp',2},
	{'a',5},
	{'w',30},
	{'walkDown',1},
	{'a',5},
	{'w',120},
	{'flyRight',9},
	{'flyDown',2},
	{'a',5},
	{'w',480},
	{'walkLeft',30},
	{'walkDown',4},
	{'walkLeft',5},
	{'walkUp',1},
	{'w',180},
	{'walkUp',9},
	{'walkLeft',7},
	{'walkUp',4},
	{'walkLeft',1},
	{'w',180},
	{'walkDown',5},
	{'walkLeft',1},
	{'talk',2}, -- TM guy
	{'walkDown',1},
	{'talk',4}, -- hyper beam
	{'walkDown',2},
	{'talk',4}, -- brick break
	{'mashB',12},
	{'walkRight',4},
	{'walkUp',6},
	{'w',180}, -- elevator
	{'walkLeft',3},
	{'walkUp',3},
	{'a',5},
	{'w',120},
	{'walkUp',3},
	{'a',5},
	{'w',240},
	{'walkRight',3},
	{'walkDown',4},
	{'w',180},
	{'walkLeft',4},
	{'walkDown',6},
	{'walkLeft',1},	
	{'talk',3},
	{'walkUp',6}, -- buy 7 XAtt
	{'talk',3},
	{'walkDown',2},
	{'a',5},
	{'w',180},
	{'walkUp',5}, -- buy 6 XSpeed
	{'talk',3},
	{'walkDown',1},
	{'a',5},
	{'w',180},
	{'walkUp',7}, -- buy 8 XSpecial
	{'talk',3},
	{'walkDown',1},
	{'a',5},
	{'w',180},
	{'walkUp',1}, -- buy 2 XAcc
	{'talk',3},
	{'mashB',8},
	{'walkUp',6},
	{'walkRight',4},
	{'walkUp',1},
	{'w',180},
	{'walkLeft',3},
	{'walkUp',3},
	{'a',5},
	{'w',120},
	{'walkDown',4},
	{'a',5},
	{'w',300},
	{'walkRight',3},
	{'walkDown',4},
	{'w',180},
	{'walkDown',5},
	{'walkRight',5},
	{'walkDown',9},
	{'w',180}, -- outside the store. teach moves
	{'s',5},
	{'w',60},
	{'walkDown',1},
	{'a',5},
	{'w',120},
	{'walkRight',1},
	{'talk',2},
	{'walkDown',3}, -- teach hyper beam
	{'a',5},
	{'w',30},
	{'a',5},
	{'w',180},
	{'walkDown',2},
	{'talk',5},
	{'w',90},
	{'walkDown',1},
	{'a',5},
	{'w',300},
	{'talk',4},
	{'w',360}, -- done. now teach thunder
	{'walkDown',1},
	{'a',5},
	{'w',30},
	{'a',5},
	{'w',180},
	{'walkDown',2},
	{'talk',5},
	{'w',90},
	{'a',5},
	{'w',300},
	{'talk',4},
	{'w',360}, --done. now brick break
	{'walkDown',1},
	{'a',5},
	{'w',30},
	{'a',5},
	{'w',180},
	{'walkUp',1},
	{'talk',5},
	{'w',90},
	{'walkDown',1},
	{'a',5},
	{'w',300},
	{'talk',4},
	{'w',360}, -- done. now rest
	{'walkDown',2},
	{'a',5},
	{'w',30},
	{'a',5},
	{'w',180},
	{'walkDown',1},
	{'talk',5},
	{'w',90},
	{'walkDown',3},
	{'a',5},
	{'w',300},
	{'talk',4},
	{'w',360},
	{'walkUp',7}, -- ive decided to teach machamp strength
	{'a',5},
	{'w',30},
	{'a',5},
	{'w',180},
	{'walkUp',1},
	{'talk',5},
	{'w',90},
	{'a',5},
	{'w',300},
	{'talk',4},
	{'w',360},

	{'mashB',12}, -- done :)
}
