lastLaugh = {
	{'w',30},
	-- Here we simply fly to the league, set up our tema, buy our items and walk to the door! We made it!!!!!!!!
	{'s',5},
	{'w',60},
	{'a',5},
	{'w',120},
	{'walkUp',2},
	{'a',5},
	{'w',30},
	{'walkDown',1},
	{'a',5},
	{'w',120},
	{'flyLeft',2},
	{'flyUp',5},
	{'a',5},
	{'w',480},
	{'walkUp',1},
	{'w',180},
	{'walkUp',4},
	{'walkRight',7},
	{'walkUp',3}, -- at the box. deposit many pokemon to update their EVs
	{'talk',5},
	{'walkDown',1},
	{'a',5},
	{'w',180},
	{'talk',6},
	{'walkDown',1},
	{'talk',9},
	{'b',5},
	{'w',30},
	{'b',5},
	{'w',120},
	{'walkUp',1},
	{'a',5},
	{'w',180},
	{'walkRight',1},
	{'talk',2},
	{'w',60},
	{'walkDown',1},
	{'walkRight',2},
	{'talk',2},
	{'w',60},
	{'walkRight',1},
	{'talk',2},
	{'w',60},
	{'walkLeft',4},
	{'walkDown',2},
	{'talk',2},
	{'w',60},
	{'walkDown',1},
	{'talk',2},
	{'w',60},
	{'mashB',12}, -- now go buy stuff
	{'walkDown',3},
	{'walkLeft',15},
	{'walkUp',6},
	{'walkLeft',2},
	{'talk',2},
	{'walkDown',2},
	{'a',5},
	{'w',180},
	{'walkUp',4},
	{'talk',3}, -- full restores
	{'walkDown',2},
	{'a',5},
	{'w',180},
	{'walkUp',2},
	{'talk',3}, -- revives
	{'mashB',12},
	{'walkRight',3},
	{'walkUp',6}, -- now just set up items
	-- Equip Cheri Berry to Machamp, Aspear Berries to Slowbro and Jolteon
	-- Silk Scarf to Gengar
	{'s',5},
	{'w',60},
	{'walkDown',1},
	{'a',5},
	{'w',120},
	{'walkRight',1},
	{'walkDown',10},
	{'talk',2},
	{'a',5},
	{'w',30},
	{'walkDown',1},
	{'a',5},
	{'w',120},
	{'walkDown',1},
	{'talk',2}, -- Cheri berry
	{'a',5},
	{'w',30},
	{'walkDown',1},
	{'talk',3}, -- Aspear on Jolteon berry
	{'a',5},
	{'w',30},
	{'walkDown',1},
	{'a',5},
	{'w',120},
	{'walkDown',2},
	{'talk',4},
	{'b',5},
	{'w',120},
	{'walkLeft',1},
	{'walkUp',3},
	{'a',5},
	{'w',30},
	{'walkDown',1},
	{'a',5},
	{'w',120},
	{'walkDown',3},
	{'talk',4},
	{'mashB',8},
	{'w',30},
}
