daycareBlitz3 = {
	{'w',30},
	-- Next! prepare for golduck, slowbro, weepinbell, butterfree, omastar
	{'s',5}, -- escape rope bc I dont want to deal with step garbage
	{'w',60},
	{'walkDown',1},
	{'a',5},
	{'w',120},
	{'walkLeft',2},
	{'walkDown',8},
	{'talk',2},
	{'w',30},
	{'a',5},
	{'w',360},
	{'s',5}, -- fly to saffron and walk to daycare
	{'w',60},
	{'walkUp',1},
	{'a',5},
	{'w',120},
	{'walkUp',2},
	{'a',5},
	{'w',30},
	{'walkDown',1},
	{'a',5},
	{'w',120},
	{'flyRight',5},
	{'flyUp',8},
	{'a',5},
	{'w',480},
	{'walkLeft',5},
	{'mashB',3}, -- repel
	{'walkLeft',3},
	{'walkUp',25},
	{'walkRight',18},
	{'walkUp',11},
	{'w',180},
	{'walkUp',8},
	{'w',180},
	{'walkUp',4},
	{'walkRight',6},
	{'walkUp',35},
	{'walkLeft',3},
	{'walkDown',3},
	{'w',60},
	{'walkDown',6},
	{'grassDown',2},
	{'walkDown',2},
	{'grassDown',2},
	{'walkDown',2},
	{'grassDown',2},
	{'walkDown',3},
	{'w',60},
	{'walkDown',6},
	{'walkLeft',5},
	{'walkUp',1},
	{'w',180}, -- in daycare
	{'walkRight',2},
	{'walkDown',1},
	{'resetMenu',1},
	{'walkRight',6}, -- to PC
	{'walkUp',6},
	{'talk',5},
	{'walkDown',2},
	{'a',5},
	{'w',120}, -- pull out psyduck, slowpoke, bellsprout, metapod, omanyte
	---------------------------------------------------------------------
	{'walkDown',3},
	{'talk',2},
	{'walkUp',5},
	{'a',5},
	{'w',120},
	{'walkUp',4},
	{'talk',2},
	{'walkDown',4},
	{'talk',2},
	{'walkLeft',1},
	{'talk',2},
	{'b',5},
	{'w',120},
	{'walkDown',2},
	{'walkLeft',1},
	{'w',30},
	{'talk',2},
	{'walkUp',4},
	{'a',5},
	{'w',120},
	{'walkUp',3},
	{'talk',2},
	{'b',5},
	{'w',120},
	{'walkDown',2},
	{'talk',2},
	{'walkUp',4},
	{'a',5},
	{'w',120},
	{'walkUp',2},
	{'talk',2},
	{'b',5},
	{'w',120},
	{'walkDown',1},
	{'talk',2},
	{'walkUp',3},
	{'a',5},
	{'w',120},
	{'talk',2},
	{'b',5},
	{'w',120},
	{'walkDown',3},
	{'talk',2},
	{'mashB',8}, -- everyone out of box. ready to run!
	----------------------------------------------------------------
	{'walkLeft',6},
	{'walkDown',4},
	{'walkLeft',2},
	{'walkUp',1}, -- drop off psyduck
 	-- psyduck begins at level 33, and evolves at lvl 33, so we just need to bring to edge of 34
	-- that takes 3366 EXP
	{'talk',4}, -- drop off psyduck
	{'w',60},
	{'walkDown',1},
	{'talk',4},
	{'leaveDaycare',1},
	{'s',5},
	{'w',60},
	{'walkDown',3},
	{'a',5},
	{'w',120},
	{'walkRight',1},
	{'walkUp',7},
	{'talk',2},
	{'w',60},
	{'bike_daycare',27},
	{'walkDown',38},
	{'walkUp',38},
	{'returnDaycare',1},
	{'w',60}, -- get psyduck back
	{'talk',6},
	-- Slowpoke might be level 20 (8000) might be higher. need to get him to level 37 at least and then use rare candy
	-- need 42653. can overshoot so I will do 362 bike routes
	{'w',30},
	{'talk',4}, -- drop off
	{'w',60},
	{'walkDown',1},
	{'talk',4},
	{'leaveDaycare',1},
	{'s',5},
	{'w',60},
	{'walkDown',3},
	{'a',5},
	{'w',120},
	{'talk',2},
	{'w',60},
	{'bike_daycare',362},
	{'returnDaycare',1},
	{'w',60}, -- get slowpoke back
	{'talk',7},
	{'w',60},
	{'w',30},
	-- bellsprout
	-- needs 4846
	{'talk',4}, -- drop off 
	{'w',60},
	{'walkDown',1},
	{'talk',4},
	{'leaveDaycare',1},
	{'s',5},
	{'w',60},
	{'walkDown',3},
	{'a',5},
	{'w',120},
	{'talk',2},
	{'w',60},
	{'bike_daycare',40},
	{'walkDown',10},
	{'walkUp',10},
	{'returnDaycare',1},
	{'w',60}, -- get bellsprout back
	{'talk',7},
	{'w',60},
	-- metapod
	{'talk',4}, -- drop off
	{'w',60},
	{'walkDown',1},
	{'talk',4},
	{'leaveDaycare',1},
	{'s',5},
	{'w',60},
	{'walkDown',3},
	{'a',5},
	{'w',120},
	{'talk',2},
	{'w',60},
	{'bike_daycare',5},
	{'walkDown',45},
	{'walkUp',45},
	{'returnDaycare',1},
	{'w',60}, -- get metapod back
	{'talk',7},
	{'w',60},
	-- omastar. going to get to 39 and then use RC (as a little time save) 
	{'talk',4}, -- drop off
	{'w',60},
	{'walkDown',1},
	{'talk',4},
	{'leaveDaycare',1},
	{'s',5},
	{'w',60},
	{'walkDown',3},
	{'a',5},
	{'w',120},
	{'talk',2},
	{'w',60},
	{'bike_daycare',479},
	{'returnDaycare',1},
	{'w',60}, -- get back
	{'talk',7},
	{'w',60},	
}
