lickitung = {
	{'w',30},
	-- at long last, our 60th pokemon. lickitung! fly to fuschia
	{'s',5},
	{'w',60},
	{'walkUp',1},
	{'a',5},
	{'w',60},
	{'a',5},
	{'walkDown',1},
	{'a',5},
	{'w',120},
	{'flyDown',6},
	{'flyRight',1},
	{'a',5},
	{'w',480},
	{'walkLeft',15},
	{'walkDown',5},
	{'walkLeft',10},
	{'walkUp',18},
	{'walkLeft',16},
	{'w',180}, -- now go upstairs
	{'walkLeft',3},
	{'walkDown',5},
	{'walkRight',3},
	{'w',180},
	{'walkUp',7},
	{'walkLeft',5},
	{'talk',3},
	{'w',30},
	{'walkDown',3},
	{'talk',3},
	{'w',60*45},
	{'talk',2}, -- hooray!
}
