tower = {
	{'w', 180}, -- BREAKPOINT
    {'walkRight', 1},
    {'w', 180},
    {'walkDown', 4},
    {'walkLeft', 2},
    {'walkDown', 3},
    --mapChange
    {'w', 180},
    {'walkLeft', 3},
    --mapChange
    {'walkUp', 40},
    {'walkLeft', 7},
    {'walkDown', 3}, -- use repel
    {'w', 30},
    {'s', 12},
    {'w', 60},
    {'a', 16},
    {'w', 60},
    {'a', 15},
    {'w', 52},
    {'a', 15},
    {'w', 180},
    {'b', 14},
    {'w', 72},
    {'b', 18},
    {'w', 114},
    {'b', 13},
    {'w', 30},
    {'walkDown', 30},
    {'w', 30},
    {'walkLeft', 4},
    {'walkDown', 6},
    {'walkRight', 4},
    {'walkUp', 2},
    {'w', 180},
    {'walkUp', 3},
    {'w', 30},
    {'a', 9}, -- get eevee back
    {'w', 132},
    {'a', 17},
    {'w', 213},
    {'a', 20},
    {'w', 169},
    {'a', 17},
    {'w', 167},
    {'a', 17},
    {'w', 167},
    {'a', 19},
    {'w', 121},
    {'a', 20}, -- end talking to daycare man
    {'w', 60},
    {'s', 12}, -- use thunderstone on eevee
    {'w', 121},
    {'a', 15},
    {'w', 180},
    {'walkDown', 1},
    {'w', 43},
    {'walkLeft', 1},
    {'w', 67},
    {'walkDown', 1},
    {'w', 53},
    {'walkLeft', 1},
    {'w', 55},
    {'walkDown', 1},
    {'walkRight', 1}, -- teach tbolt
    {'w', 338},
    {'a', 12},
    {'w', 166},
    {'a', 11},
    {'w', 360},
    {'walkDown', 1},
    {'w', 180},
	{'talk',2},
	{'walkDown',2},
	{'talk',6},
	{'w',240},
	{'talk',4},
	{'w',300}, -- now equip rest to charizard lol
	{'walkDown',3},
	{'a',5},
	{'w',30},
	{'walkDown',1},
	{'a',5},
	{'w',90},
	{'walkDown',1},
	{'talk',2},
	{'walkUp',2},
	{'mashB',10},
	-- cerulean 3
    {'w', 60},
    {'s', 13}, -- move jolteon to front of party
    {'w', 103},
	{'walkUp',1},
    {'a', 15},
    {'w', 150},
    {'walkLeft', 1},
    {'w', 60},
    {'walkRight', 1},
    {'w', 60},
    {'walkDown', 1},
    {'w', 60},
    {'walkRight', 1},
    {'w', 58},
    {'walkDown', 1},
    {'w', 60},
    {'a', 16},
    {'w', 60},
    {'walkDown', 1},
    {'w', 60},
    {'a', 23},
    {'w', 75},
    {'walkLeft', 1},
    {'w', 106},
    {'a', 21},
    {'w', 177},
    {'b', 26},
    {'w', 83},
    {'b', 22}, -- done moving
    {'w', 40}, -- go back to lavender
    {'walkDown', 4},
    {'w', 240},
    {'walkRight', 2},
    {'walkDown', 2},
    {'w', 60},
    {'walkDown', 5},
    {'w', 180},
    {'walkDown', 9}, -- out into saffron
    {'w', 180},
    {'walkDown', 9},
    {'walkRight', 19},
    {'walkDown', 9},
    {'walkLeft', 14},
    {'walkDown', 3},
    {'walkRight', 2},
    {'w', 120},
    {'press_b', 4},
    {'walkRight', 12},
    {'walkDown', 3},
    {'walkRight', 8},
    {'w', 180},
    {'walkRight', 13}, -- out to route 7
    --mapChange
    {'w', 180},
    {'walkUp', 3}, -- go to lavender 
    {'w', 30},
    {'walkRight', 12},
    {'walkDown', 7},
    {'walkRight', 9},
    {'walkUp', 13},
    {'walkRight', 30},
    {'walkDown', 13},
    {'walkRight', 7},
    {'walkDown', 2},
    {'walkRight', 4},
    {'walkUp', 5},
    --mapChange
    {'walkRight', 15},
    {'walkDown', 3},
    {'walkRight', 8},
    {'walkUp', 6},
    {'walkUp', 1},
    {'walkRight', 6},
    {'walkUp', 3}, -- into pokemon tower
    --mapChange
    {'w', 540},
    -- lavender-1
    {'walkRight', 2},
    {'w', 38},
    {'walkUp', 3},
    {'w', 44},
    {'walkRight', 3},
    {'w', 32},
    {'walkUp', 7},
    {'w', 32},
    {'walkRight', 5},
    {'w', 24},
    {'walkUp', 2},
    {'w', 60},
    {'walkRight', 2}, -- up stairs to first floor
    --mapChange
    {'w', 216},
    {'s', 11}, -- use repel (and setup future repels)
    {'w', 296},
    {'walkDown', 1},
    {'w', 116},
    {'a', 14},
    {'w', 223},
    {'walkLeft', 1},
    {'w', 209},
    {'walkUp', 1},
    {'walkUp', 1},
    {'walkUp', 1},
    {'w', 58},
    {'a', 17},
    {'w', 116},
    {'a', 13},
    {'w', 183},
    {'b', 22},
    {'w', 52},
    {'b', 22},
    {'w', 71},
    {'b', 27}, -- end menu
    {'w', 60},
    {'walkUp', 6}, -- goto rival
    {'walkLeft', 2},
    {'w', 180},
    {'b', 11},
    {'w', 153},
    {'b', 11},
    {'w', 127},
    {'b', 13},
    {'w', 152},
    {'b', 19},
    {'w', 452},
    {'b', 21},
    {'w', 444},
    {'use_move', 5}, -- defeat rival
    {'press_b', 6},
    {'w', 60},
    {'walkLeft', 8},
    {'walkDown', 2},
    {'walkLeft', 6},
    {'walkDown', 5},
    {'walkLeft', 2}, -- up one floor
    --mapChange
    {'w', 180},
    {'walkDown', 5},
    {'walkRight', 6},
    {'walkUp', 3},
    {'w', 228},
    {'b', 11},
    {'w', 442},
    {'b', 15},
    {'w', 483},
    {'a', 19},
    {'w', 47},
    {'w', 33},
    {'use_move', 1}, -- defeat ghost trainer
    {'press_b', 5},
    {'walkDown', 4}, -- go to next trainer
    {'walkRight', 2},
    {'w', 232},
    {'b', 16},
    {'w', 467},
    {'b', 17},
    {'w', 495},
    {'a', 10},
    {'w', 68},
    {'use_move', 1},
    {'press_b', 5}, -- defeat next ghost trainer
    {'walkRight', 5},
    {'walkUp', 2},
    {'walkRight', 3},
    {'walkUp', 5},
    {'walkRight', 3}, -- up another floor
    -- mapChange
    {'w', 180},
    {'walkLeft', 2}, -- goto next trainer
    {'w', 232},
    {'b', 14},
    {'w', 445},
    {'b', 14},
    {'w', 448},
    {'a', 18},
    {'use_move', 2},
    {'press_b', 4},
    {'walkLeft', 3},
    {'w', 27},
    {'walkDown', 2},
    {'w', 25},
    {'walkLeft', 3},
    {'w', 123},
    {'a', 14},
    {'w', 194},
    {'b', 16},
    {'w', 62},
    {'walkRight', 3},
    {'w', 36},
    {'walkUp', 6},
    {'w', 60},
    {'walkLeft', 5},
    {'w', 22},
    {'walkUp', 4},
    {'w', 31},
    {'walkLeft', 5},
    {'w', 23},
    {'walkDown', 2},
    {'w', 23},
    {'walkLeft', 3},
    {'w', 37},
    {'walkDown', 7},
    {'w', 159},
    {'walkDown', 2},
    {'w', 156},
    {'b', 19},
    {'w', 434},
    {'b', 21},
    {'w', 437},
    {'a', 22},
    {'w', 32},
    {'use_move', 1},
    {'press_b', 4},
    {'walkUp', 3},
    {'walkLeft', 3},
    {'w', 180}, -- up to next floor
    {'walkUp', 5},
    {'w', 37},
    {'walkRight', 7},
    {'w', 39},
    {'walkUp', 2},
    {'w', 30},
    {'walkRight', 2},
    {'walkUp', 1},
    {'a', 13},
    {'w', 85},
    {'a', 17},
    {'w', 481},
    {'b', 24},
    {'w', 400},
    {'a', 12},
    {'w', 38},
    {'use_move', 1},
    {'press_b', 4},
    {'walkRight', 3},
    {'walkDown', 2},
    {'w', 30},
    {'s', 15}, -- apply repel
    {'w', 30},
    {'a', 12},
    {'w', 80},
    {'a', 13},
    {'w', 30},
    {'a', 12},
    {'w', 90},
    {'b', 14},
    {'w', 61},
    {'b', 17},
    {'w', 82},
    {'b', 14},
    {'w', 60},
    {'walkDown', 1},
    {'s', 15}, -- apply repel
    {'w', 30},
    {'a', 12},
    {'w', 80},
    {'a', 13},
    {'w', 30},
    {'a', 12},
    {'w', 90},
    {'b', 14},
    {'w', 61},
    {'b', 17},
    {'w', 82},
    {'b', 14},
    {'w', 60},
    {'walkDown', 2},
    {'w', 25},
    {'walkLeft', 2},
    {'w', 149},
    {'b', 21},
    {'w', 66},
    {'b', 18},
    {'w', 64},
    {'walkRight', 3},
    {'w', 51},
    {'walkUp', 3},
    {'w', 46},
    {'walkRight', 3},
    {'w', 186},
    {'b', 22},
    {'w', 412},
    {'b', 24},
    {'w', 424},
    {'a', 12},
    {'w', 42},
    {'use_move', 1},
    {'press_b', 3},
    {'walkUp', 2},
    {'w', 39},
    {'walkRight', 3},
    {'w', 45},
    {'walkDown', 5},
    {'w', 46},
    {'walkRight', 2},
    --mapChange
    {'w', 180}, -- up another floor
    {'walkLeft', 2},
    {'w', 207},
    {'a', 20}, -- fight trainer
    {'w', 428},
    {'b', 25},
    {'w', 463},
    {'a', 21},
    {'use_move', 3},
    {'press_b', 4}, -- switch to gyarados
	{'s',5},
	{'w',60},
	{'walkUp',1},
	{'a',5},
	{'w',120},
	{'a',5},
	{'w',30},
	{'walkDown',1},
	{'a',5},
	{'w',30},
	{'walkDown',3},
	{'a',5},
	{'w',90},
	{'mashB',8},
    {'walkUp', 5},
    {'w', 225},
    {'b', 13}, -- fight trainer
    {'w', 420},
    {'b', 22},
    {'w', 390},
    {'a', 15},
    {'w', 26},
    {'use_move', 1},
    {'press_b', 4},
    {'walkUp', 3}, -- to next trainer
    {'walkLeft', 6},
    {'walkDown', 4},
    {'walkLeft', 3},
    {'w', 200},
    {'b', 20}, -- fight trainer
    {'w', 431},
    {'b', 25},
    {'w', 495},
    {'a', 18},
    {'w', 33},
    {'use_move', 1},
    {'press_b', 4},
    {'walkLeft', 4},
    {'walkDown', 8},
    {'w', 31},
    {'a', 15},
    {'w', 186},
    {'b', 26},
    {'w', 54},
    {'walkUp', 3},
    {'w', 44},
    {'walkRight', 7},
    {'w', 42},
    {'walkDown', 4},
    {'w', 219},
    {'b', 16}, -- fight marowak
    {'w', 406},
    {'b', 21},
    {'w', 381},
    {'b', 29},
    {'w', 346},
    {'a', 18},
    {'w', 117},
    {'use_move', 1},
    {'press_b', 5},
    {'walkDown', 1},
    {'walkLeft', 2}, -- up another floor
    {'w', 180},
    {'walkUp', 7},
    {'w', 200},
    {'b', 15},
    {'w', 380},
    {'b', 18},
    {'w', 480},
    {'use_move', 3},
    {'press_b', 5},
    {'walkUp', 2},
    {'w', 217},
    {'a', 20},
    {'w', 163},
    {'b', 24},
    {'w', 147},
    {'b', 22},
    {'w', 403},
    {'b', 23},
    {'w', 487},
    {'use_move', 2},
    {'press_b', 5},
    {'walkUp', 2},
    {'w', 185},
    {'b', 27},
    {'w', 451},
    {'b', 23},
    {'w', 488},
    {'use_move', 4},
    {'press_b', 5},
    {'walkUp', 1},
    {'w', 60},
    {'a', 19}, -- talk to mr. fuji
    {'w', 132},
    {'b', 25},
    {'w', 157},
    {'b', 23},
    {'w', 114},
    {'b', 28},
    {'w', 209},
    {'b', 20},
    {'w', 112},
    {'b', 26},
    {'w', 227},
    {'b', 22}, -- back to fuji's house
    --mapChange
    {'w', 200},
    {'w', 233},
    {'walkUp', 4},
    {'w', 40},
    {'walkLeft', 1},
    {'w', 40},
    {'a', 12}, -- talk to fuji
    {'w', 140},
    {'b', 20},
    {'w', 105},
    {'b', 31},
    {'w', 74},
    {'b', 35},
    {'w', 67},
    {'b', 46},
    {'w', 52},
    {'b', 40},
    {'w', 142},
    {'b', 38},
    {'w', 51},
    {'b', 45},
    {'w', 51},
    {'b', 42}, -- pokeflute acquired 
    {'w', 60},
    {'walkDown', 6},
    {'w', 180},-- switch jolteon to front
	{'s',5},
	{'w',60},
	{'a',5},
	{'w',120},
	{'walkUp',2},
	{'a',5},
	{'w',30},
	{'walkDown',1},
	{'a',5},
	{'w',30},
	{'walkLeft',1},
	{'a',5},
	{'w',120},
	{'b',5},
	{'w',120},
	{'walkDown',1},
	{'b',5},
	{'w',60},
}
