trade2FR = {
	{'w',30}, -- first player. start with a reset game	{'w',1},
	{'w',350},
	{'a',5},
	{'w',350},
	{'a',5},
	{'w',350},
	{'s',5},
	{'w',200},
	{'a',5}, -- now mash B through annoying boxes
	{'mashB',35},
	{'talk',8},
	{'w',600},
	{'talk',8},
	{'w',120}, -- in trade room
	{'walkUp',2},
	{'walkLeft',1},
	{'walkUp',1},
	{'w',720}, -- first trade mime for omanyte
	{'a',5},
	{'w',30},
	{'walkDown',1},
	{'a',5},
	{'w',600},
	{'a',5},
	{'w',60*90}, -- trade done. now pinsir for metapod
	{'walkRight',1},
	{'a',5},
	{'w',30},
	{'walkDown',1},
	{'a',5},
	{'w',600},
	{'a',5},
	{'w',60*90}, -- trade done. now hitmonchan for aero
	{'walkDown',1},
	{'a',5},
	{'w',30},
	{'walkDown',1},
	{'a',5},
	{'w',600},
	{'a',5},
	{'w',60*90}, -- trade done. now porygon for gyarados
	{'walkDown',1},
	{'walkRight',1},
	{'a',5},
	{'w',30},
	{'walkDown',1},
	{'a',5},
	{'w',600},
	{'a',5},
	{'w',60*90}, -- trade done. now pidgeot for slowpoke
	{'walkDown',2},
	{'a',5},
	{'w',30},
	{'walkDown',1},
	{'a',5},
	{'w',600},
	{'a',5},
	{'w',60*90}, -- trade done. now hitmonlee for bellsprout
	{'walkDown',2},
	{'walkRight',1},
	{'a',5},
	{'w',30},
	{'walkDown',1},
	{'a',5},
	{'w',600},
	{'a',5},
	{'w',60*90}, -- trades done. 
	{'walkLeft',1},
	{'walkUp',1},
	{'talk',2},
	{'w',300},
	{'walkDown',1},
	{'walkRight',1},
	{'walkDown',3},
	{'w',240}, -- terminate
	{'talk',8},
	{'w',600},
}
